### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by Callidus2000** [unbekanntes-pferd/DRACOON-SPRAYER#5]
Tried to use the sprayer app which resulted in the following error:
```
Traceback (most recent call last):
  File "/usr/local/bin/dracoon-sprayer", line 5, in <module>
    from dracoonsprayer.cli import app
  File "/usr/local/lib/python3.10/site-packages/dracoonsprayer/cli.py", line 2, in <module>
    from dracoonsprayer.util.dracoon_auth import password_flow, auth_code_flow
  File "/usr/local/lib/python3.10/site-packages/dracoonsprayer/util/dracoon_auth.py", line 1, in <module>
    from dracoon import core
ImportError: cannot import name 'core' from 'dracoon' (/usr/local/lib/python3.10/site-packages/dracoon/__init__.py)
```

Also tried it in a fresh docker environment:
```
docker run -it --rm --name my-Python python:3 bash
python3 -m pip install dracoon-sprayer
# No Error
root@6b76ace129a4:/# dracoon-sprayer --help
# results in error above
```

**Comment by unbekanntes-pferd** [comment]
Thanks for the report -  this is caused by a newer version of the 'dracoon' package. I'll update dracoon-sprayer this week - meanwhile it should work using an older version of the 'dracoon' package (`pip install dracoon==0.3.0`) in a virtual env.
